# version: "3"
services:
  db_redis:
    image: redis
    container_name: db_redis
    command: redis-server --requirepass ${SERVER_DB_PASSWORD}
    restart: always
    ports:
      - "${SERVER_DB_PORT}:6379"
    volumes:
      - db_redis_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  db_redis_data: